import { ProductInformationProvisionNotice } from '@src/interface/ProductInterface';

export const ProductStatusOptions = [
  { key: '001', name: '판매중' },
  { key: '002', name: '대기중' },
  { key: '003', name: '품절' },
  { key: '004', name: '판매중지' },
];

export const ProductSaleArea = [
  { key: '001', name: '전국' },
  { key: '002', name: '서울' },
  { key: '003', name: '경기도' },
  { key: '004', name: '충청도' },
  { key: '005', name: '강원도' },
  { key: '006', name: '전라도' },
  { key: '007', name: '경상도' },
  { key: '008', name: '제주도' },
];

export const ProductDeliveryOptions = [
  { key: '001', name: '무료배송' },
  { key: '002', name: '선결제' },
  { key: '003', name: '착불' },
  { key: '004', name: '조건부배송' },
];

export const ProductCountryOriginOptions = [
  { key: 'KO', name: '대한민국' },
  { key: 'USA', name: '미국' },
  { key: 'JP', name: '일본' },
  { key: 'CH', name: '중국' },
  { key: 'RU', name: '러시아' },
  { key: 'UK', name: '영국' },
  { key: 'VI', name: '베트남' },
  { key: 'AU', name: '호주' },
];

export const ProductInformationProvisionNoticeItems = [
  { itemCode: 'WEAR', name: '의류' },
  { itemCode: 'SHOES', name: '구두 / 신발' },
  { itemCode: 'BAG', name: '가방' },
  { itemCode: 'FASHION_ITEMS', name: '패션잡화 (모자 / 벨트 / 액세서리 등)' },
  { itemCode: 'SLEEPING_GEAR', name: '침구류 / 커튼' },
  { itemCode: 'FURNITURE', name: '가구 (침대 / 소파 / 싱크대 / DIY제품 등' },
  { itemCode: 'IMAGE_APPLIANCES', name: '영상가전 (TV류)' },
  { itemCode: 'HOME_APPLIANCES', name: '가정용 전기제품 (냉장고 / 세탁기 / 식기세척기 / 전자레인지 등)' },
  { itemCode: 'SEASON_APPLIANCES', name: '계절가전 (에어컨 / 온풍기 등)' },
  { itemCode: 'OFFICE_APPLIANCES', name: '사무용기긱 (컴퓨터 / 노트북 / 프린터 등)' },
  { itemCode: 'OPTICS_APPLIANCES', name: '광학기기 (디지털카메라 / 캠코터 등)' },
  { itemCode: 'MICROELECTRONICS', name: '소형가전 (MP3 / 전자사전 등)' },
  { itemCode: 'PORTABLE_DEVICE', name: '휴대형 통신기기 (휴대폰 / 태블릿 등)' },
  { itemCode: 'NAVIGATION', name: '내비게이션' },
  { itemCode: 'CAR_ARTICLES', name: '자동차용품 (자동차부품 / 기타 자동차용품 등)' },
  { itemCode: 'MEDICAL_APPLIANCES', name: '의료기기' },
  { itemCode: 'KITCHEN_UTENSILS', name: '주방용품' },
  { itemCode: 'COSMETIC', name: '화장품' },
  { itemCode: 'JEWELLERY', name: '귀금속 / 보석 / 시계류' },
  { itemCode: 'FOOD', name: '농수축산물' },
  { itemCode: 'GENERAL_FOOD', name: '가공식품' },
  { itemCode: 'DIET_FOOD', name: '건강기능식품' },
  { itemCode: 'KIDS', name: '어린이제품' },
  { itemCode: 'MUSICAL_INSTRUMENT', name: '악기' },
  { itemCode: 'SPORTS_EQUIPMENT', name: '스포츠용품' },
  { itemCode: 'BOOKS', name: '서적' },
  { itemCode: 'RESERVATION', name: '호텔 / 펜션 예약' },
  { itemCode: 'TRAVEL_PACKAGE', name: '여행패키지' },
  { itemCode: 'AIRLINE_TICKET', name: '항공권' },
  { itemCode: 'RENTAL_CAR', name: '자동차 대여 서비스 (렌터카)' },
  { itemCode: 'RENTAL_APPLIANCES', name: '물품대여 서비스(정수기, 비데, 공기청정기 등)' },
  { itemCode: 'RENTAL_ETC', name: '물품대여 서비스(서적, 유아용품, 행사용품 등)' },
  { itemCode: 'DIGITAL_CONTENTS', name: '디지털 콘텐츠 (음원, 게임, 인터넷강의 등)' },
  { itemCode: 'GIFT_CARD_COUPON', name: '상품권 / 쿠폰' },
  { itemCode: 'MOBILE_COUPON', name: '모바일 쿠폰' },
  { itemCode: 'MOVIE', name: '영화ㆍ공연' },
  { itemCode: 'HOUSE_CHEMICAL', name: '생활화학제품' },
  { itemCode: 'BIOCIDAL', name: '살생물제품' },
  { itemCode: 'ETC_SERVICE', name: '기타 용역' },
  { itemCode: 'ETC', name: '기타 재화' },
];

export const ProductInformationProvisionNoticeItemDetail: ProductInformationProvisionNotice = {
  WEAR: [
    {
      key: 'material',
      name: '제품 소재 (섬유의 조성 또는 혼용율을 백분율로 표시, 기능성인 경우 성적서 또는 허가서)',
      value: '',
    },
    { key: 'color', name: '색상', value: '' },
    { key: 'size', name: '치수', value: '' },
    {
      key: 'manufacturer',
      name: '제조자, 수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)',
      value: '',
    },
    { key: 'countryOfManufacture', name: '제조국', value: '' },
    { key: 'washing', name: '세탁방법 및 취급시 주의사항', value: '' },
    { key: 'dateOfManufacture', name: '제조연월', value: '' },
    { key: 'quality', name: '품질보증기준', value: '' },
    { key: 'afterServiceTelecom', name: 'A/S 책임자와 전화번호', value: '' },
  ],
  SHOES: [
    { key: 'material', name: '제품 주소재 (운동화인 경우에는 겉감, 안감을 구분하여 표시)', value: '' },
    { key: 'color', name: '색상', value: '' },
    { key: 'size', name: '발길이', value: '' },
    { key: 'height', name: '굽높이', value: '' },
    {
      key: 'manufacturer',
      name: '제조자, 수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능) ',
      value: '',
    },
    { key: 'countryOfManufacture', name: '제조국 ', value: '' },
    { key: 'caution', name: '취급시 주의사항', value: '' },
    { key: 'dateOfManufacture', name: '제조연월', value: '' },
    { key: 'quality', name: '품질보증기준', value: '' },
    { key: 'afterServiceTelecom', name: 'A/S 책임자와 전화번호', value: '' },
  ],
  BAG: [
    { key: 'type', name: '종류', value: '' },
    { key: 'material', name: '소재', value: '' },
    { key: 'color', name: '색상', value: '' },
    { key: 'size', name: '크기', value: '' },
    {
      key: 'manufacturer',
      name: '제조자, 수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능) ',
      value: '',
    },
    { key: 'countryOfManufacture', name: '제조국 ', value: '' },
    { key: 'caution', name: '취급시 주의사항', value: '' },
    { key: 'quality', name: '품질보증기준', value: '' },
    { key: 'afterServiceTelecom', name: 'A/S 책임자와 전화번호', value: '' },
  ],
  FASHION_ITEMS: [
    { key: 'type', name: '종류', value: '' },
    { key: 'material', name: '소재', value: '' },
    { key: 'size', name: '치수', value: '' },
    {
      key: 'manufacturer',
      name: '제조자, 수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능) ',
      value: '',
    },
    { key: 'countryOfManufacture', name: '제조국 ', value: '' },
    { key: 'caution', name: '취급시 주의사항', value: '' },
    { key: 'quality', name: '품질보증기준', value: '' },
    { key: 'afterServiceTelecom', name: 'A/S 책임자와 전화번호', value: '' },
  ],
  SLEEPING_GEAR: [
    { key: 'material', name: '제품 소재 (섬유의 조성 또는 혼용률을 백분율로 표시)', value: '' },
    { key: 'color', name: '색상', value: '' },
    { key: 'size', name: '크기', value: '' },
    { key: 'package', name: '제품구성', value: '' },
    {
      key: 'manufacturer',
      name: '제조자, 수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능) ',
      value: '',
    },
    { key: 'countryOfManufacture', name: '제조국 ', value: '' },
    { key: 'washing', name: '세탁방법 및 취급시 주의사항', value: '' },
    { key: 'quality', name: '품질보증기준', value: '' },
    { key: 'afterServiceTelecom', name: 'A/S 책임자와 전화번호', value: '' },
  ],
  FURNITURE: [
    { key: 'name', name: '품명', value: '' },
    { key: 'kc', name: 'KC 인증정보', value: '' },
    { key: 'color', name: '색상', value: '' },
    { key: 'package', name: '구성품', value: '' },
    { key: 'material', name: '주요 소재', value: '' },
    {
      key: 'manufacturer',
      name: '제조자, 수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능) ',
      value: '',
    },
    { key: 'countryOfManufacture', name: '제조국 ', value: '' },
    { key: 'size', name: '크기', value: '' },
    { key: 'refurbishment', name: '재공급(리퍼브) 가구의 경우 재공급 사유 및 하자 부위에 관한 정보', value: '' },
    { key: 'delivery', name: '배송 및 설치', value: '' },
    { key: 'quality', name: '품질보증기준', value: '' },
    { key: 'afterServiceTelecom', name: 'A/S 책임자와 전화번호', value: '' },
  ],
};
